# Generated by Django 4.2 on 2024-04-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_managers_remove_user_username"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_blocked_partner",
            new_name="is_blocked",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_partner",
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("client", "Client"),
                    ("partner", "Partner"),
                    ("staff", "Staff"),
                ],
                default="Client",
                max_length=15,
            ),
            preserve_default=False,
        ),
    ]
