# Generated by Django 4.2 on 2024-04-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_rename_is_blocked_partner_user_is_blocked_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("client", "Client"),
                    ("partner", "Partner"),
                    ("admin", "Admin"),
                ],
                max_length=15,
            ),
        ),
    ]
