# Generated by Django 4.2 on 2024-04-19 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("partner", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="establishment",
            name="location",
        ),
        migrations.AddField(
            model_name="establishment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default="2020-05-27"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="establishment",
            name="location_char",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="establishment",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="establishment_logos/"
            ),
        ),
        migrations.AddField(
            model_name="establishment",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="establishment",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="establishment",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="establishment",
            name="phone_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
