# Generated by Django 4.2 on 2024-04-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partner", "0005_qrcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="establishment",
            name="happyhours_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="establishment",
            name="happyhours_start",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
