# Generated by Django 4.2 on 2024-04-29 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("beverage", "0003_alter_beverage_category"),
    ]

    operations = []
