# Generated by Django 4.2 on 2024-04-29 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("beverage", "0008_alter_beverage_category"),
    ]

    operations = []
